export interface Experiences {
  /** Stable key for trackBy / anchors. */
  id: string;
  /** ISO date. Durations and labels are derived from it, never hard-coded. */
  start: string;
  /** ISO date, or null when this is the current role. */
  end: string | null;
  location: string;
  company: string;
  role: string;
  /** The stack actually written in this role. */
  technologies: string[];
  /** Workflow tooling - kept separate from the stack on purpose. */
  tools?: string[];
  /**
   * Each line is written as "Lead-in: detail" and is split on the first colon
   * when rendered, so the scanning eye gets a bolded label per bullet.
   */
  responsibilities: string[];
}

export const experiencesDataEn: Experiences[] = [
  {
    id: 'elca',
    start: '2023-11-15',
    end: null,
    location: 'Palermo, Italy',
    role: 'Senior Frontend Developer',
    company: 'Elca Spa',
    technologies: [
      'Angular',
      'React',
      'TypeScript',
      'NgRx',
      'HTML',
      'CSS',
      'Electron Framework',
      'Ionic',
      'Java',
      'C#',
      'Cypress',
      'Jest',
    ],
    tools: [
      'Jenkins',
      'GitLab CI',
      'Git',
      'Jira',
      'Trello',
      'IntelliJ IDEA',
      'Visual Studio Code',
      'Chrome DevTools',
      'Figma',
      'Notion',
      'Slack',
      'Agile development',
    ],
    responsibilities: [
      'Development & Delivery of Internal Projects: Successfully led the development and deployment of two high-impact internal projects, ensuring robust architectures, maintainability, and adherence to best practices.',
      "Porting to Angular 20 and Mastery of New Features: I successfully led the porting project to Angular 20, gaining in-depth knowledge of its new features such as Signals, thereby enhancing our application's performance and functionality.",
      'Consulting for Swisscom: Provided expertise in frontend and backend development to maintain and enhance Swisscom’s main portal, implementing new features and resolving complex issues with a focus on performance and scalability.',
      'Reusable Component Library Development: Designed and developed external React and Angular libraries, standardizing UI components across multiple projects, improving code reusability, and streamlining development workflows.',
      'Cross-Technology Contributions: Worked on an external project, bridging React and Angular implementations while integrating backend services in Java, contributing to a more modular and efficient system.',
      'Hybrid App Development: Developed a hybrid app for desktop and mobile using Ionic (iOS, Android) and Electron (Windows, macOS) for router management. The backend was implemented in C#.',
      'Test Automation & CI/CD Pipelines: Implemented comprehensive test suites using Jest and Cypress, while optimizing CI/CD pipelines with Jenkins and GitLab CI, enhancing reliability and deployment efficiency.',
      'Technical Interviews & Talent Acquisition: Conducted multiple technical interviews to assess and onboard developers, ensuring a high technical standard within the team.',
      'Technical Speaking & Knowledge Sharing: Delivered a talk at Beer Tech on frontend best practices and scalable architectures, fostering engagement within the development community.',
    ],
  },
  {
    id: 'gpi',
    start: '2021-08-31',
    end: '2023-11-14',
    location: 'Palermo, Italy',
    company: 'GPI spa',
    role: 'Senior Frontend Team Leader - Full Stack Developer',
    technologies: [
      'Angular 2+ (v12)',
      'TypeScript',
      'HTML',
      'CSS',
      'Java Spring Boot',
      'RESTful APIs',
    ],
    tools: [
      'Jenkins',
      'GitLab',
      'Git',
      'Jira',
      'Trello',
      'IntelliJ IDEA',
      'Visual Studio Code',
      'Chrome DevTools',
      'Postman',
      'OpenAPI',
      'YAML',
      'Figma',
      'Notion',
      'Slack',
    ],
    responsibilities: [
      'Frontend Architecture & Development: Designed and implemented a scalable, high-performance frontend framework, ensuring seamless integration with backend services.',
      'Team Leadership & Mentorship: Led and mentored a team of two Junior Frontend Developers, fostering a collaborative and high-performance Agile environment.',
      'API Integration & Quality Assurance: Developed frontend functionality, integrated RESTful APIs, and conducted rigorous API testing to ensure data accuracy, security, and system reliability.',
      'Code Quality & Maintenance: Led continuous bug fixing, performance optimization, and code refactoring to enhance system stability. Reviewed code submissions for best practices, performance, and maintainability.',
      'Branch Management & Deployment: Oversaw Git workflow, branch management, code merging, and deployment processes, ensuring smooth development cycles.',
      'Cross-Team Collaboration: Worked closely with the Backend Team Leader to align frontend and backend architecture, improving scalability and maintainability.',
    ],
  },
  {
    id: 'arancia-ict',
    start: '2018-09-30',
    end: '2021-08-30',
    location: 'Palermo, Italy',
    company: 'Arancia-ict (Bank consultant)',
    role: 'Full-Stack Developer Consultant',
    technologies: [
      'Angular 2+',
      'Xframes',
      'Java Spring Framework',
      'SQL',
      'Oracle',
    ],
    tools: [
      'Jenkins',
      'GitLab',
      'Git',
      'Bitbucket',
      'Subversion (SVN)',
      'Jira',
      'Trello',
      'IntelliJ IDEA',
      'Eclipse',
      'Visual Studio Code',
      'Chrome DevTools',
      'Postman',
      'OpenAPI',
      'YAML',
      'Google Cloud Platform',
      'Figma',
      'Notion',
      'Slack',
    ],
    responsibilities: [
      'Web Application Development & Management: Designed, developed, and maintained web applications, ensuring high performance and reliability.',
      'Bug Fixing & Performance Optimization: Diagnosed and resolved issues to minimize downtime, enhance user experience, and improve system efficiency.',
      'Client Support & Consulting: Provided technical assistance, addressed client requests, and implemented required changes to meet business needs.',
      'Cross-Team Collaboration: Worked with developers, designers, and business stakeholders to deliver scalable, secure, and high-performing solutions.',
    ],
  },
  {
    id: 'gft',
    start: '2017-12-31',
    end: '2018-09-30',
    location: 'Milano, Italy',
    company: 'GFT Italia',
    role: 'Java Backend Developer - Consulting',
    technologies: ['Java', 'Spring Framework', 'JUnit', 'Oracle', 'Maven'],
    responsibilities: [
      "Banking APIs: I worked as a Backend Developer in a banking environment, where my main responsibility was to develop and implement new APIs to support and enhance the institution's internal systems. Specifically, I focused on designing and creating scalable and secure solutions, enabling seamless integration between various banking services and applications.",
    ],
  },
  {
    id: 'lookout',
    start: '2017-03-31',
    end: '2017-12-31',
    location: 'Palermo, Italy',
    company: 'Lookout S.r.L.',
    role: 'Mobile Developer - Ionic Framework',
    technologies: ['AngularJs', 'Ionic Framework'],
    responsibilities: [
      "Geolocation Tracking App: I developed an app using Ionic and AngularJS, designed to track users' routes, manage login authentication, and record the time spent at specific locations. The app integrated geolocation features to monitor movements in real time while ensuring secure access and accurate time logging for each position. This project involved both frontend and backend integration to provide a smooth, responsive user experience.",
    ],
  },
];

export const experiencesDataIt: Experiences[] = [
  {
    id: 'elca',
    start: '2023-11-15',
    end: null,
    location: 'Palermo, Italia ',
    role: 'Senior Frontend Developer',
    company: 'Elca Spa',
    technologies: [
      'Angular',
      'React',
      'TypeScript',
      'NgRx',
      'HTML',
      'CSS',
      'Electron Framework',
      'Ionic',
      'Java',
      'C#',
      'Cypress',
      'Jest',
    ],
    tools: [
      'Jenkins',
      'GitLab CI',
      'Git',
      'Jira',
      'Trello',
      'IntelliJ IDEA',
      'Visual Studio Code',
      'Chrome DevTools',
      'Figma',
      'Notion',
      'Slack',
      'Sviluppo Agile',
    ],
    responsibilities: [
      'Sviluppo e Consegna di Progetti Interni: Ho guidato con successo lo sviluppo e il rilascio di due progetti interni di alto impatto, garantendo architetture robuste, manutenibilità e rispetto delle migliori pratiche.',
      'Porting ad Angular 20 e Padronanza delle Nuove Funzionalità: Ho guidato con successo il progetto di porting ad Angular 20, acquisendo una conoscenza approfondita delle sue nuove funzionalità come i Signals, migliorando così le prestazioni e la funzionalità della nostra applicazione.',
      'Consulenza per Swisscom: Fornita esperienza nello sviluppo frontend e backend per mantenere e migliorare il portale principale di Swisscom, implementando nuove funzionalità e risolvendo problemi complessi con un focus su prestazioni e scalabilità.',
      'Sviluppo di Librerie di Componenti Riutilizzabili: Progettato e sviluppato librerie esterne React e Angular, standardizzando i componenti UI attraverso diversi progetti, migliorando la riutilizzabilità del codice e ottimizzando i flussi di lavoro di sviluppo.',
      'Contributi Cross-Technology: Ho lavorato su un progetto esterno, unendo implementazioni React e Angular e integrando servizi backend in Java, contribuendo a un sistema più modulare ed efficiente.',
      "Sviluppo App Ibride: Sviluppato un'app ibrida per desktop e mobile utilizzando Ionic (iOS, Android) ed Electron (Windows, macOS) per la gestione dei router. Il backend era implementato in C#.",
      "Automazione dei Test e Pipeline CI/CD: Implementate suite di test complete utilizzando Jest e Cypress, ottimizzando le pipeline CI/CD con Jenkins e GitLab CI, migliorando l'affidabilità e l'efficienza del deployment.",
      "Colloqui Tecnici e Acquisizione Talenti: Condotto numerosi colloqui tecnici per valutare e inserire sviluppatori, garantendo un elevato standard tecnico all'interno del team.",
      'Speaking Tecnico e Condivisione della Conoscenza: Tenuto un intervento al Beer Tech sulle migliori pratiche frontend e architetture scalabili, favorendo il coinvolgimento nella community di sviluppo.',
    ],
  },
  {
    id: 'gpi',
    start: '2021-08-31',
    end: '2023-11-14',
    location: 'Palermo, Italia',
    company: 'GPI spa',
    role: 'Senior Frontend Team Leader - Full Stack Developer',
    technologies: [
      'Angular 2+ (v12)',
      'TypeScript',
      'HTML',
      'CSS',
      'Java Spring Boot',
      'API RESTful',
    ],
    tools: [
      'Jenkins',
      'GitLab',
      'Git',
      'Jira',
      'Trello',
      'IntelliJ IDEA',
      'Visual Studio Code',
      'Chrome DevTools',
      'Postman',
      'OpenAPI',
      'YAML',
      'Figma',
      'Notion',
      'Slack',
    ],
    responsibilities: [
      "Architettura Frontend e Sviluppo: Progettato e implementato un framework frontend scalabile ad alte prestazioni, garantendo un'integrazione perfetta con i servizi backend.",
      'Leadership del Team e Mentorship: Guidato e fatto da mentore a un team di due Junior Frontend Developers, promuovendo un ambiente Agile collaborativo e ad alte prestazioni.',
      'Integrazione API e Quality Assurance: Sviluppato funzionalità frontend, integrato API RESTful e condotto rigorosi test API per garantire accuratezza dei dati, sicurezza e affidabilità del sistema.',
      "Qualità del Codice e Manutenzione: Guidato il bug fixing continuo, l'ottimizzazione delle prestazioni e il refactoring del codice per migliorare la stabilità del sistema. Revisionato le sottomissioni di codice per best practices, prestazioni e manutenibilità.",
      'Gestione dei Branch e Deployment: Supervisionato il flusso di lavoro Git, la gestione dei branch, il merge del codice e i processi di deployment, garantendo cicli di sviluppo fluidi.',
      "Collaborazione Cross-Team: Lavorato a stretto contatto con il Backend Team Leader per allineare l'architettura frontend e backend, migliorando scalabilità e manutenibilità.",
    ],
  },
  {
    id: 'arancia-ict',
    start: '2018-09-30',
    end: '2021-08-30',
    location: 'Palermo, Italia',
    company: 'Arancia-ict (Consulente Bancario)',
    role: 'Full-Stack Developer Consultant',
    technologies: [
      'Angular 2+',
      'Xframes',
      'Java Spring Framework',
      'SQL',
      'Oracle',
    ],
    tools: [
      'Jenkins',
      'GitLab',
      'Git',
      'Bitbucket',
      'Subversion (SVN)',
      'Jira',
      'Trello',
      'IntelliJ IDEA',
      'Eclipse',
      'Visual Studio Code',
      'Chrome DevTools',
      'Postman',
      'OpenAPI',
      'YAML',
      'Google Cloud Platform',
      'Figma',
      'Notion',
      'Slack',
    ],
    responsibilities: [
      'Sviluppo e Gestione Applicazioni Web: Progettato, sviluppato e mantenuto applicazioni web, garantendo alte prestazioni e affidabilità.',
      "Bug Fixing e Ottimizzazione Prestazioni: Diagnosticato e risolto problemi per minimizzare i tempi di inattività, migliorare l'esperienza utente e l'efficienza del sistema.",
      'Supporto Clienti e Consulenza: Fornito assistenza tecnica, gestito le richieste dei clienti e implementato le modifiche richieste per soddisfare le esigenze aziendali.',
      'Collaborazione Cross-Team: Lavorato con sviluppatori, designer e stakeholder aziendali per fornire soluzioni scalabili, sicure e ad alte prestazioni.',
    ],
  },
  {
    id: 'gft',
    start: '2017-12-31',
    end: '2018-09-30',
    location: 'Milano, Italia',
    company: 'GFT Italia',
    role: 'Java Backend Developer - Consulenza',
    technologies: ['Java', 'Spring Framework', 'JUnit', 'Oracle', 'Maven'],
    responsibilities: [
      "API Bancarie: Ho lavorato come Backend Developer in ambito bancario, dove la mia responsabilità principale era sviluppare e implementare nuove API per supportare e migliorare i sistemi interni dell'istituto. Nello specifico, mi sono concentrato sulla progettazione e creazione di soluzioni scalabili e sicure, consentendo un'integrazione perfetta tra vari servizi bancari e applicazioni.",
    ],
  },
  {
    id: 'lookout',
    start: '2017-03-31',
    end: '2017-12-31',
    location: 'Palermo, Italia',
    company: 'Lookout S.r.L.',
    role: 'Mobile Developer - Ionic Framework',
    technologies: ['AngularJs', 'Ionic Framework'],
    responsibilities: [
      "App di Tracciamento e Geolocalizzazione: Ho sviluppato un'app utilizzando Ionic e AngularJS, progettata per tracciare i percorsi degli utenti, gestire l'autenticazione di login e registrare il tempo trascorso in luoghi specifici. L'app integrava funzionalità di geolocalizzazione per monitorare i movimenti in tempo reale garantendo al contempo un accesso sicuro e una registrazione accurata del tempo per ogni posizione. Questo progetto ha coinvolto l'integrazione frontend e backend per fornire un'esperienza utente fluida e reattiva.",
    ],
  },
];
